## Mall Customer Segmentation ML Project (K-Mean Algorithm) -

In [57]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [58]:
df = pd.read_csv("C:/Users/chaud/OneDrive/Desktop/DARSHAN/MY PROJECTS/Mall Customer Segmentation ML/Raw_Mall_Customers_Data.csv")

In [59]:
df.head()


CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [60]:
df.shape

(200, 5)

In [61]:
df.describe()

CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  200.000000          200.000000              200.000000
mean   100.500000   38.850000           60.560000               50.200000
std     57.879185   13.969007           26.264721               25.823522
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   28.750000           41.500000               34.750000
50%    100.500000   36.000000           61.500000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

In [62]:
df.dtypes

CustomerID                 int64
Gender                    object
Age                        int64
Annual Income (k$)         int64
Spending Score (1-100)     int64
dtype: object

In [63]:
df.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [64]:
df.drop(['CustomerID'], axis = 1, inplace = True)

In [65]:
df.head()

Gender  Age  Annual Income (k$)  Spending Score (1-100)
0    Male   19                  15                      39
1    Male   21                  15                      81
2  Female   20                  16                       6
3  Female   23                  16                      77
4  Female   31                  17                      40

# EXPLORATORY DATA ANALYSIS

In [66]:
df.columns

Index(['Gender', 'Age', 'Annual Income (k$)', 'Spending Score (1-100)'], dtype='object')

In [67]:
sns.distplot(df['Annual Income (k$)'], bins = 10)

<IPython.core.display.Javascript object>

<Axes: xlabel='Annual Income (k$)', ylabel='Density'>

In [68]:
plt.figure(1, figsize=(15,6))                 #  sets the size of the figure to be 15 units in width and 6 units in height
n=0
for x in ['Age', 'Annual Income (k$)', 'Spending Score (1-100)']:
    n+=1
    plt.subplot(1 ,3 ,n)                               # creates a subplot grid with 1 row and 3 columns and selects the nth subplot
    plt.subplots_adjust(hspace = 0.5, wspace = 0.5)    # Adjusting Subplot Spacing
    sns.distplot(df[x], bins = 10)                     # specifies the number of bins to use for binning the data.
    plt.title('Distplot of {}'.format(x))
plt.show()

<IPython.core.display.Javascript object>

In [69]:
plt.figure(1, figsize = (15,5))
sns.countplot(y= 'Gender', data = df)
plt.show()

<IPython.core.display.Javascript object>

In [70]:
sns.violinplot(x = 'Annual Income (k$)', y= 'Gender', data= df)

<IPython.core.display.Javascript object>

<Axes: xlabel='Annual Income (k$)', ylabel='Gender'>

In [71]:
plt.figure(1, figsize=(15,7))
n=0
for cols in ['Age', 'Annual Income (k$)', 'Spending Score (1-100)']:
    n+=1
    plt.subplot(1 ,3 ,n)
    sns.set(style = 'whitegrid')
    plt.subplots_adjust(hspace = 0.5, wspace = 0.5)
    sns.violinplot(x = cols, y= 'Gender', data= df)
    plt.ylabel('Gender' if n==1 else '')
    plt.title('Violin Plot {}'.format(cols))
plt.show()

<IPython.core.display.Javascript object>

In [72]:
age_18_25 = df.Age[(df.Age >= 18) & (df.Age <= 25)]
age_26_35 = df.Age[(df.Age >= 26) & (df.Age <= 35)]
age_36_45 = df.Age[(df.Age >= 36) & (df.Age <= 45)]
age_46_55 = df.Age[(df.Age >= 46) & (df.Age <= 55)]
age_56_70 = df.Age[(df.Age >= 56)]

In [73]:
age_18_25

0      19
1      21
2      20
3      23
5      22
7      23
13     24
15     22
17     20
21     25
29     23
31     21
33     18
35     21
39     20
41     24
45     24
61     19
65     18
68     19
78     23
84     21
87     22
91     18
95     24
99     20
100    23
105    21
111    19
113    19
114    18
115    19
124    23
132    25
134    20
138    19
144    25
162    19
Name: Age, dtype: int64

In [74]:
agex = ['18-25', '26-35', '36-45', '46-55', '56-70']
agey = [len(age_18_25.values), len(age_26_35.values), len(age_36_45.values), len(age_46_55.values), len(age_56_70.values)]

In [75]:
sns.barplot(x=agex, y=agey, palette= 'mako')            # color palette to be used for the bars

<IPython.core.display.Javascript object>

<Axes: >

In [76]:
plt.figure(figsize = (15,6))
sns.barplot(x=agex, y=agey, palette= 'mako')  # color palette to be used for the bars
plt.title('Number of Customer and Age')
plt.xlabel('Age')
plt.ylabel('Number of Customer')
plt.show()

<IPython.core.display.Javascript object>

In [77]:
sns.relplot(x = 'Annual Income (k$)', y = 'Spending Score (1-100)',  data = df)

<IPython.core.display.Javascript object>

In [78]:
df.columns

Index(['Gender', 'Age', 'Annual Income (k$)', 'Spending Score (1-100)'], dtype='object')

In [79]:
SS_1_20 = df['Spending Score (1-100)'][(df['Spending Score (1-100)'] >= 1) & (df['Spending Score (1-100)'] <= 20)]
SS_21_40 = df['Spending Score (1-100)'][(df['Spending Score (1-100)'] >= 21) & (df['Spending Score (1-100)'] <= 40)]
SS_41_60 = df['Spending Score (1-100)'][(df['Spending Score (1-100)'] >= 41) & (df['Spending Score (1-100)'] <= 60)]
SS_61_80 = df['Spending Score (1-100)'][(df['Spending Score (1-100)'] >= 61) & (df['Spending Score (1-100)'] <= 80)]
SS_81_100 = df['Spending Score (1-100)'][(df['Spending Score (1-100)'] >= 81) & (df['Spending Score (1-100)'] <= 100)]

SSx = ['1-20', '21-40', '41-60', '61-80', '81-100']
SSy = [len(SS_1_20.values), len(SS_21_40.values), len(SS_41_60.values), len(SS_61_80.values), len(SS_81_100.values)]

In [80]:
plt.figure(figsize=(15,6))
sns.barplot(x=SSx, y=SSy, palette='rocket')
plt.title('Spending Score')
plt.xlabel('Score')
plt.ylabel('Number of cutomer having Spending Score')
plt.show()

<IPython.core.display.Javascript object>

In [81]:
ai_10_30 = df['Annual Income (k$)'][(df['Annual Income (k$)'] >= 10) & (df['Annual Income (k$)'] <= 30)]
ai_31_60 = df['Annual Income (k$)'][(df['Annual Income (k$)'] >= 31) & (df['Annual Income (k$)'] <= 60)]
ai_61_90 = df['Annual Income (k$)'][(df['Annual Income (k$)'] >= 61) & (df['Annual Income (k$)'] <=90)]
ai_91_120 = df['Annual Income (k$)'][(df['Annual Income (k$)'] >= 91) & (df['Annual Income (k$)'] <= 120)]
ai_121_150 = df['Annual Income (k$)'][(df['Annual Income (k$)'] >= 121) & (df['Annual Income (k$)'] <= 150)]

aix = ['$ 0-30,000','$ 30,001-60,000','$ 60,001-90,000','$ 90,001-1,20,000','$ 1,20,001-1,50,000']
aiy = [len(ai_10_30.values), len(ai_31_60.values), len(ai_61_90.values), len(ai_91_120.values), len(ai_121_150.values)]

In [82]:
plt.figure(figsize=(15,6))
sns.barplot(x=aix, y=aiy, palette='Spectral')
plt.title('Annual Incomes')
plt.ylabel('Incomes')
plt.xlabel('Number of Customer')
plt.show()

<IPython.core.display.Javascript object>

# K-MEAN AGORITHM

In [83]:
X1=df.loc[:, ["Age", "Spending Score (1-100)"]].values  

'''This line selects two columns, "Age" and "Spending Score (1-100)", from the DataFrame df.
    selects all rows (:) and the specified columns.
    .values = converts the selected columns into a NumPy array (X1), which is a format suitable for use with scikit-learn.'''

from sklearn.cluster import KMeans                        # This imports the KMeans class from scikit-learn's clustering module.
wcss = []

for k in range(1,11):
    kmean = KMeans(n_clusters=k, init="k-means++")
    kmean.fit(X1)
    wcss.append(kmean.inertia_)
    
''' This loop iterates over the range from 1 to 10 (inclusive), representing different numbers of clusters (k).
    For each value of k, it creates a KMeans object with n_clusters=k and init="k-means++".
    The "k-means++" initialization method selects initial cluster centers in a way that speeds up convergence.
    kmeans.fit(X1) = fits the KMeans model to the data X1.
    kmeans.inertia_ = represents the within-cluster sum of squared distances to the nearest centroid. and appends it to the wcss list.'''
    
plt.figure(figsize=(15,6))
plt.grid()
plt.plot(range(1,11), wcss, linewidth=2, color="red", marker="8") # plots the range of cluster numbers (from 1 to 10) against the corresponding WCSS values.
plt.xlabel('K Value')
plt.ylabel('wcss')
plt.show()

<IPython.core.display.Javascript object>

In [84]:
X1

array([[19, 39],
       [21, 81],
       [20,  6],
       [23, 77],
       [31, 40],
       [22, 76],
       [35,  6],
       [23, 94],
       [64,  3],
       [30, 72],
       [67, 14],
       [35, 99],
       [58, 15],
       [24, 77],
       [37, 13],
       [22, 79],
       [35, 35],
       [20, 66],
       [52, 29],
       [35, 98],
       [35, 35],
       [25, 73],
       [46,  5],
       [31, 73],
       [54, 14],
       [29, 82],
       [45, 32],
       [35, 61],
       [40, 31],
       [23, 87],
       [60,  4],
       [21, 73],
       [53,  4],
       [18, 92],
       [49, 14],
       [21, 81],
       [42, 17],
       [30, 73],
       [36, 26],
       [20, 75],
       [65, 35],
       [24, 92],
       [48, 36],
       [31, 61],
       [49, 28],
       [24, 65],
       [50, 55],
       [27, 47],
       [29, 42],
       [31, 42],
       [49, 52],
       [33, 60],
       [31, 54],
       [59, 60],
       [50, 45],
       [47, 41],
       [51, 50],
       [69, 46],
       [27, 51

In [85]:
wcss

[171535.50000000003,
 75949.15601023019,
 45840.67661610866,
 28172.705092506112,
 23818.411688187858,
 19764.10311679061,
 17152.71949993472,
 13054.17214598267,
 12319.32520901142,
 10451.299348943285]

In [86]:
kmean1 = KMeans(n_clusters=4)

label1 = kmean1.fit_predict(X1)

print(label1)

[3 0 1 0 3 0 1 0 1 0 1 0 1 0 1 0 3 3 1 0 3 0 1 0 1 0 1 3 1 0 1 0 1 0 1 0 1
 0 1 0 2 0 2 3 1 3 2 3 3 3 2 3 3 2 2 2 2 2 3 2 2 3 2 2 2 3 2 2 3 3 2 2 2 2
 2 3 2 3 3 2 2 3 2 2 3 2 2 3 3 2 2 3 2 3 3 3 2 3 2 3 3 2 2 3 2 3 2 2 2 2 2
 3 3 3 3 3 2 2 2 2 3 3 3 0 3 0 2 0 1 0 1 0 3 0 1 0 1 0 1 0 1 0 3 0 1 0 2 0
 1 0 1 0 1 0 1 0 1 0 1 0 2 0 1 0 1 0 1 0 1 3 1 0 1 0 1 0 1 0 1 0 1 0 1 0 2
 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0]


In [87]:
print(kmean1.cluster_centers_)

[[30.1754386  82.35087719]
 [43.29166667 15.02083333]
 [55.40816327 48.04081633]
 [27.32608696 49.36956522]]


In [88]:
plt.scatter(X1[:,0], X1[:,1], c=kmean1.labels_, cmap='rainbow')     #represent the first and second columns of the array X1, respectively. 

plt.scatter(kmean1.cluster_centers_[:,0], kmean1.cluster_centers_[:,1], color = 'black')

plt.title('Clusters of Customer')

plt.ylabel('Spending Score (1-100)')

plt.xlabel('Age')

<IPython.core.display.Javascript object>

Text(0.5, 0, 'Age')

In [89]:
df.columns

Index(['Gender', 'Age', 'Annual Income (k$)', 'Spending Score (1-100)'], dtype='object')

In [90]:
X2 = df.loc[:, ['Annual Income (k$)', 'Spending Score (1-100)']].values

In [91]:
X2

array([[ 15,  39],
       [ 15,  81],
       [ 16,   6],
       [ 16,  77],
       [ 17,  40],
       [ 17,  76],
       [ 18,   6],
       [ 18,  94],
       [ 19,   3],
       [ 19,  72],
       [ 19,  14],
       [ 19,  99],
       [ 20,  15],
       [ 20,  77],
       [ 20,  13],
       [ 20,  79],
       [ 21,  35],
       [ 21,  66],
       [ 23,  29],
       [ 23,  98],
       [ 24,  35],
       [ 24,  73],
       [ 25,   5],
       [ 25,  73],
       [ 28,  14],
       [ 28,  82],
       [ 28,  32],
       [ 28,  61],
       [ 29,  31],
       [ 29,  87],
       [ 30,   4],
       [ 30,  73],
       [ 33,   4],
       [ 33,  92],
       [ 33,  14],
       [ 33,  81],
       [ 34,  17],
       [ 34,  73],
       [ 37,  26],
       [ 37,  75],
       [ 38,  35],
       [ 38,  92],
       [ 39,  36],
       [ 39,  61],
       [ 39,  28],
       [ 39,  65],
       [ 40,  55],
       [ 40,  47],
       [ 40,  42],
       [ 40,  42],
       [ 42,  52],
       [ 42,  60],
       [ 43,

In [92]:
wcss1 = []

for k in range(1,11):
    kmeans = KMeans(n_clusters = k, init = 'k-means++')
    kmeans.fit(X2)
    wcss1.append(kmeans.inertia_)


In [93]:
wcss1

[269981.28,
 186362.95600651755,
 106348.37306211122,
 73679.78903948836,
 67292.92248638248,
 37455.98455516028,
 31924.23890692641,
 26144.893738044906,
 28818.893635531134,
 20721.635019841277]

In [94]:
plt.plot(range(1,11), wcss1 ,linewidth=2, color="green", marker="8")

<IPython.core.display.Javascript object>

In [95]:
kmean2 = KMeans(n_clusters = 5)

label2 = kmean2.fit_predict(X2)

print(label2)

[3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3 4 3
 4 3 4 3 4 3 0 3 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 2 1 0 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 0 1 2 1 2 1
 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1 2
 1 2 1 2 1 2 1 2 1 2 1 2 1 2 1]


In [96]:
print(kmean2.cluster_centers_)

[[55.0875     49.7125    ]
 [86.53846154 82.12820513]
 [87.75       17.58333333]
 [26.30434783 20.91304348]
 [25.72727273 79.36363636]]


In [97]:
plt.scatter(X2[:, 0], X2[:, 1], c=kmean2.labels_, cmap='rainbow')

plt.scatter(kmean2.cluster_centers_[:, 0], kmean2.cluster_centers_[:, 1], color = 'black')

plt.title('Clusters of Customer')

plt.ylabel('Spending Score (1-100)')

plt.xlabel('Annual Income (k$)')

<IPython.core.display.Javascript object>

Text(0.5, 0, 'Annual Income (k$)')

In [98]:
X3 = df.iloc[:, 1:]

In [99]:
X3

Age  Annual Income (k$)  Spending Score (1-100)
0     19                  15                      39
1     21                  15                      81
2     20                  16                       6
3     23                  16                      77
4     31                  17                      40
..   ...                 ...                     ...
195   35                 120                      79
196   45                 126                      28
197   32                 126                      74
198   32                 137                      18
199   30                 137                      83

[200 rows x 3 columns]

In [100]:
wcss2 = []

for k in range(1,11):
    kmean = KMeans(n_clusters = k, init = 'k-means++')
    kmean.fit(X3)
    wcss2.append(kmean.inertia_)

In [101]:
wcss2

[308812.78,
 212840.1698209719,
 143342.751571706,
 104366.15145556197,
 75493.84464013917,
 58338.70237980935,
 51424.18365800865,
 49234.43612268957,
 45133.96529581529,
 38370.41154401154]

In [102]:
plt.plot(range(1,11), wcss2, linewidth=2, color="blue", marker="8")

<IPython.core.display.Javascript object>

In [103]:
kmean3 = KMeans(n_clusters = 5)

label3 = kmean3.fit_predict(X3)

print(label3)

[4 1 4 1 4 1 4 1 4 1 4 1 4 1 4 1 4 1 4 1 4 1 4 1 4 1 4 1 4 1 4 1 4 1 4 1 4
 1 4 1 4 1 4 1 4 1 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 2 0 2 3 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2
 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0
 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2]


In [104]:
print(kmean3.cluster_centers_)

[[40.32432432 87.43243243 18.18918919]
 [25.52173913 26.30434783 78.56521739]
 [32.69230769 86.53846154 82.12820513]
 [43.28205128 55.02564103 49.69230769]
 [45.2173913  26.30434783 20.91304348]]


In [105]:
clusters = kmean3.fit_predict(X3)

In [106]:
clusters

array([4, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4,
       1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4,
       1, 4, 1, 3, 3, 3, 1, 3, 3, 1, 1, 1, 1, 1, 3, 1, 1, 3, 1, 1, 1, 3,
       3, 1, 3, 3, 1, 1, 1, 1, 1, 3, 3, 3, 3, 1, 1, 3, 1, 3, 3, 3, 3, 3,
       3, 3, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 3, 3, 1, 3, 1, 1,
       1, 3, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 3, 0, 3, 0, 3, 0, 2, 0, 2, 0,
       3, 0, 2, 0, 2, 0, 2, 0, 2, 0, 3, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0,
       2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0,
       2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0,
       2, 0])

In [107]:
df["label"] = clusters

In [108]:
%matplotlib notebook
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

fig = plt.figure(figsize = (20,10))

# adds a 3D subplot to the figure. The 111 means a single subplot, and '3d' specifies the projection to be 3D.
ax = fig.add_subplot(111, projection = '3d')

''' These lines create scatter plots in 3D.
    Each ax.scatter() call plots data points with different cluster labels (label) in different colors.
    For each cluster label (0 to 4), it selects data points based on their labels and plots them with different colors (blue, red, green, orange, and purple).'''

ax.scatter(df.Age[df.label == 0], df['Annual Income (k$)'][df.label == 0], df['Spending Score (1-100)'][df.label == 0], c='blue', s = 60)
ax.scatter(df.Age[df.label == 1], df['Annual Income (k$)'][df.label == 1], df['Spending Score (1-100)'][df.label == 1], c='red', s = 60)
ax.scatter(df.Age[df.label == 2], df['Annual Income (k$)'][df.label == 2], df['Spending Score (1-100)'][df.label == 2], c='green', s = 60)
ax.scatter(df.Age[df.label == 3], df['Annual Income (k$)'][df.label == 3], df['Spending Score (1-100)'][df.label == 3], c='orange', s = 60)
ax.scatter(df.Age[df.label == 4], df['Annual Income (k$)'][df.label == 4], df['Spending Score (1-100)'][df.label == 4], c='purple', s = 60)


#  sets the elevation and azimuthal angles of the 3D plot. 
#  The first argument (30) sets the elevation angle, and the second argument (185) sets the azimuthal angle.
ax.view_init(30, 185)  

plt.xlabel('Age')
plt.ylabel('Annual Income (k$)')
ax.set_zlabel('Spending Score (1-100)')

plt.show()


<IPython.core.display.Javascript object>

In [109]:
df.columns

Index(['Gender', 'Age', 'Annual Income (k$)', 'Spending Score (1-100)',
       'label'],
      dtype='object')

In [110]:
df.head()

Gender  Age  Annual Income (k$)  Spending Score (1-100)  label
0    Male   19                  15                      39      4
1    Male   21                  15                      81      4
2  Female   20                  16                       6      1
3  Female   23                  16                      77      4
4  Female   31                  17                      40      1

## 